[en]
languageName = "En"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
footer_menu_left = "Company"
footer_menu_middle = "Services"
footer_menu_right = "Support"
footer_content = """
KvK 77548175<br>
BTW NL003206132B57<br>
The Hague, The Netherlands
"""
copyright = """
Copyright © 2022 Ver Artis |
Banner image adapted from [Freepik](https://www.freepik.com/free-vector/architecture-historic-old-buildings-al-lineart-style-set_11447513.htm) |
Website powered by [Hugo](https://gohugo.io/)
"""
# SEO meta data for OpenGraph / Twitter Card
[en.metadata]
author = "Ver Artis"
image = "images/logo-wb.png"
description = "Guided tours in museums and cities in the Netherlands"
keywords = [
  "VerArtis",
  "Museum",
  "City",
  "Guided tour",
  "Guide",
  "Tour",
  "Netherlands",
]

[it]
languageName = "It"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 2
footer_menu_left = "Azienda"
footer_menu_middle = "Servizi"
footer_menu_right = "Supporto"
footer_content = """
KvK 77548175<br>
BTW NL003206132B57<br>
L'Aia, Paesi Bassi
"""
copyright = """
Copyright © 2022 Ver Artis |
Banner image adapted from [Freepik](https://www.freepik.com/free-vector/architecture-historic-old-buildings-al-lineart-style-set_11447513.htm) |
Website powered by [Hugo](https://gohugo.io/)
"""
# SEO meta data for OpenGraph / Twitter Card
[it.metadata]
author = "Ver Artis"
image = "images/logo-wb.png"
description = "Visite guidate a musei e città nei Paesi Bassi"
keywords = [
  "VerArtis",
  "Museum",
  "City",
  "Guided tour",
  "Guide",
  "Tour",
  "Netherlands",
]
