################################################################################
# Main menu
################################################################################

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "services/"
weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

################################################################################
# Footer menu
################################################################################

[[footer_left]]
name = "Museum tours"
weight = 1
url = "services/"

[[footer_left]]
name = "City tours"
weight = 2
url = "services/"

[[footer_left]]
name = "Custom tours"
weight = 3
url = "services/"

[[footer_middle]]
name = "Stories"
weight = 1
url = "stories/"

[[footer_middle]]
name = "About us"
weight = 2
url = "about/"

[[footer_middle]]
name = "Contact"
weight = 3
url = "team/"

[[footer_right]]
name = "FAQ"
weight = 1
url = "faq/"

[[footer_right]]
name = "Terms & conditions"
weight = 2
url = "conditions/"

[[footer_right]]
name = "Privacy policy"
weight = 3
url = "privacy/"
