################################################################################
# Images
################################################################################

# Favicon
favicon = "images/favicon.png"

# Logo
logo = "images/logo.svg"
# logo_dark = "images/logo-dark.png"

# Logo width. Note: does not work with .svg file, in header, but works with
# .svg file in footer
logo_width = "100px"

# If false, will not generate WEBP version of logo
logo_webp = true

# Logo text will only show when logo is missing
logo_text = "Ver Artis"

################################################################################
# Behavior
################################################################################

# Theme mode
theme_switcher = false
theme_default = "light"  # available options: light, dark, automatic

# Copyright
theme_copyright = true
copyright = "Copyright © 2022 Ver Artis"

# Contact form action
contact_form_action = "https://api.verartis.com/v1/contactform"

# hCaptcha site key
hcaptcha_sitekey = "cba967ec-da86-477a-8c30-ddb176201e2e"

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format

# Navigation button
[navigation_button]
enable = false
label = "Get started"
link = "contact/"

################################################################################
# Colors and fonts
################################################################################

[variables]

# Primary color (buttons, links, icons)
color_primary = "#1C6336"

# Secondary color (footer)
color_secondary = "#710C36"

# Color of the background of main sections (light theme / dark theme)
body_color = "#FFFFFF"
dark_body_color = "#1E262C"
# body_color = "#FFF5E4"

# Color of the background of alternate sections (light theme / dark theme)
light = "#EDF6F5"
dark = "#1B2229"
# light = "#FFF5E4"

# Color of main text (light theme / dark theme)
text_color = "#777777"
dark_text_color = "#CBCBCB"

# Color of headers and menu titles (light theme / dark theme)
text_dark = "#222222"
dark_text_dark = "#FFFFFF"

# Color of text in footer
text_light = "#CCCCCC"
dark_text_light = "#959595"

# Border of tables and footer top rule (light theme / dark theme)
border_color = "#CCCCCC"
dark_border_color = "#4E4E4E"

# Color of cards (light theme / dark theme)
white = "#FFFFFF"
black = "#101418"

# Go to https://fonts.google.com/ to find the font you want to use. select your
# font and copy only the bold part from the URL. and paste it here. example:
# "Work+Sans:wght@400;500;600"
font_primary = "Bree+Serif"
font_primary_type = "serif"  # serif/sans-serif
font_secondary = "PT+Sans:ital,wght@0,400;0,700;1,400;1,700"
font_secondary_type = "sans-serif"  # serif/sans-serif

# When font_location is "local", we need to have a stylesheet
# (static/css/fonts.css) that provides the @font-face declarations for the
# fonts specified above 
font_location = "local"  # local/google

font_size = "24px"  # default is 16px
font_scale = "1.125"  # default is 1.25 ("majorThird")

################################################################################
# Analytics
################################################################################

# Matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # Your matomo url
id = ""  # Your matomo id

# Cookies
[cookies]
enable = false
expire_days = 2
content = """
This site uses cookies.
By continuing to using this website, you agree to their use.
"""
button = "I Accept"

################################################################################
# Plugins
################################################################################

# Reset array of CSS plugins, so as to not import by default those specified by
# themes/bigspring/config.toml
plugins.css = []

# Default CSS plugins (from themes/bigspring/config.toml). We're not importing
# Font Awesome from the theme's module because they pull the font from a CDN
# (https://github.com/gethugothemes/hugo-modules/tree/master/icons/font-awesome)
[[plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/brands.css"
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/solid.css"
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/regular.css"
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/icons.css"

# Default JS plugins
[[plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[plugins.js]]
link = "plugins/glightbox.js"
[[plugins.js]]
link = "plugins/cookie.js"
[[plugins.js]]
link = "plugins/lazy-loader.js"

# Custom JS plugins
[[plugins.js]]
link = "plugins/form.js"
