################################################################################
# Images
################################################################################

# Favicon
favicon = "images/favicon.png"

# Logo
logo = "images/logo.svg"
# logo_dark = "images/logo-dark.png"

# Logo width. Note: does not work with .svg file, in header, but works with
# .svg file in footer
logo_width = "100px"

# If false, will not generate WEBP version of logo
logo_webp = true

# Logo text will only show when logo is missing
logo_text = "Ver Artis"

################################################################################
# Behavior
################################################################################

# Theme mode
theme_switcher = false
theme_default = "light"  # available options: light, dark, automatic

# Copyright
theme_copyright = true
copyright = "Copyright © 2022 Ver Artis"

# Contact form action
# contact_form_action = "https://formspree.io/f/mlevarky"
contact_form_action = "https://formsubmit.co/13e6d85f07e95fd91d13a2979e34dbbb"

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format

# Navigation button
[navigation_button]
enable = false
label = "Get started"
link = "contact/"

################################################################################
# Colors and fonts
################################################################################

[variables]

# Accent color (buttons, links, icons)
color_primary = "#1C6336"

# ???
# color_secondary = "#671B67"

# Color of the background
# body_color = "#FFF5E4"

# Color of the background of alternate sections
# light = "#FFF"

# Go to https://fonts.google.com/ to find the font you want to use. select your
# font and copy only the bold part from the URL. and paste it here. example:
# "Work+Sans:wght@400;500;600"
font_primary = "Bree+Serif"
font_primary_type = "serif"  # serif/sans-serif
font_secondary = "PT+Sans:ital,wght@0,400;0,700;1,400;1,700"
font_secondary_type = "sans-serif"  # serif/sans-serif

# When font_location is "local", we need to have a stylesheet
# (static/css/fonts.css) that provides the @font-face declarations for the
# fonts specified above 
font_location = "local"  # local/google

font_size = "24px"  # default is 16px
font_scale = "1.125"  # default is 1.25 ("majorThird")

################################################################################
# Analytics
################################################################################

# Matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # Your matomo url
id = ""  # Your matomo id

# Cookies
[cookies]
enable = false
expire_days = 2
content = """
This site uses cookies.
By continuing to using this website, you agree to their use.
"""
button = "I Accept"
